// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilkStore.Data;

#nullable disable

namespace MilkStore.Migrations
{
    [DbContext(typeof(MilkstoreDbContext))]
    partial class MilkstoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MilkStore.Models.CardDetail", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cardId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("cardNumber");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("cvv");

                    b.Property<string>("UserEmailId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User_emailId");

                    b.HasKey("CardId")
                        .HasName("PK__CardDeta__4D5BC491844A3D3D");

                    b.HasIndex("UserEmailId");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("MilkStore.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ProductProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("UserEmailId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User_emailId");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__415B03B88746E28E");

                    b.HasIndex("ProductProductId");

                    b.HasIndex("UserEmailId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("MilkStore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalAmount");

                    b.Property<int>("TrackingNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("UserEmailId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User_emailId");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__0809335DA27F7321");

                    b.HasIndex("UserEmailId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MilkStore.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int")
                        .HasColumnName("Orders_orderId");

                    b.Property<decimal>("PriceAtOrder")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("priceAtOrder");

                    b.Property<int>("ProductProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("TrackingNumber")
                        .HasColumnType("int")
                        .HasColumnName("trackingNumber");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("OrderDetailsId")
                        .HasName("PK__OrderIte__5EEE527321D87DB5");

                    b.HasIndex("OrdersOrderId");

                    b.HasIndex("ProductProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MilkStore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("EstimatedDelivery")
                        .HasColumnType("datetime2")
                        .HasColumnName("estimatedDelivery");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productName");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stockQuantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__2D10D16ACCDF16A4");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("MilkStore.Models.ShipmentDetail", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deliveryDate");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("deliveryStatus");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int")
                        .HasColumnName("Orders_orderId");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("shippingAddress");

                    b.HasKey("ShipmentId")
                        .HasName("PK__Shipment__472178019705953B");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("ShipmentDetails");
                });

            modelBuilder.Entity("MilkStore.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("paymentMode");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("paymentStatus");

                    b.Property<decimal>("TotalAmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalAmountPaid");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transactionDate");

                    b.Property<string>("UserEmailId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("User_emailId");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__9B57CF7229E9D5AC");

                    b.HasIndex("UserEmailId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MilkStore.Models.User", b =>
                {
                    b.Property<string>("EmailId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("emailId");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.Property<int?>("PinCode")
                        .HasColumnType("int")
                        .HasColumnName("pinCode");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.HasKey("EmailId")
                        .HasName("PK__Users__87355E72966BE19D");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MilkStore.Models.CardDetail", b =>
                {
                    b.HasOne("MilkStore.Models.User", "UserEmail")
                        .WithMany("CardDetails")
                        .HasForeignKey("UserEmailId")
                        .IsRequired()
                        .HasConstraintName("FK__CardDetai__User___534D60F1");

                    b.Navigation("UserEmail");
                });

            modelBuilder.Entity("MilkStore.Models.Cart", b =>
                {
                    b.HasOne("MilkStore.Models.Product", "ProductProduct")
                        .WithMany("Carts")
                        .HasForeignKey("ProductProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__Product_pr__4316F928");

                    b.HasOne("MilkStore.Models.User", "UserEmail")
                        .WithMany("Carts")
                        .HasForeignKey("UserEmailId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__User_email__4222D4EF");

                    b.Navigation("ProductProduct");

                    b.Navigation("UserEmail");
                });

            modelBuilder.Entity("MilkStore.Models.Order", b =>
                {
                    b.HasOne("MilkStore.Models.User", "UserEmail")
                        .WithMany("Orders")
                        .HasForeignKey("UserEmailId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__User_ema__47DBAE45");

                    b.Navigation("UserEmail");
                });

            modelBuilder.Entity("MilkStore.Models.OrderItem", b =>
                {
                    b.HasOne("MilkStore.Models.Order", "OrdersOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__4CA06362");

                    b.HasOne("MilkStore.Models.Product", "ProductProduct")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductProductId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Produ__4D94879B");

                    b.Navigation("OrdersOrder");

                    b.Navigation("ProductProduct");
                });

            modelBuilder.Entity("MilkStore.Models.ShipmentDetail", b =>
                {
                    b.HasOne("MilkStore.Models.Order", "OrdersOrder")
                        .WithMany("ShipmentDetails")
                        .HasForeignKey("OrdersOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__ShipmentD__Order__5629CD9C");

                    b.Navigation("OrdersOrder");
                });

            modelBuilder.Entity("MilkStore.Models.Transaction", b =>
                {
                    b.HasOne("MilkStore.Models.User", "UserEmail")
                        .WithMany("Transactions")
                        .HasForeignKey("UserEmailId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__User___5070F446");

                    b.Navigation("UserEmail");
                });

            modelBuilder.Entity("MilkStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ShipmentDetails");
                });

            modelBuilder.Entity("MilkStore.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MilkStore.Models.User", b =>
                {
                    b.Navigation("CardDetails");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
